const CMS=window.HappyCMS;
const IMG=window.HappyImageStore;
let data=CMS.get();
const $=s=>document.querySelector(s);
const toast=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)};
const CFG_KEY='happyFroebelCloudV15';
function cfg(){try{return JSON.parse(localStorage.getItem(CFG_KEY)||'{}')}catch{return {}}}
function saveCfg(v){localStorage.setItem(CFG_KEY,JSON.stringify(v))}
function api(path,options={}){const c=cfg();if(!c.workerUrl||!c.adminKey)throw new Error('클라우드 연결정보를 먼저 저장하세요.');return fetch(c.workerUrl.replace(/\/$/,'')+path,{...options,headers:{'content-type':'application/json','x-admin-key':c.adminKey,...(options.headers||{})}}).then(async r=>{const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(j.error||'서버 요청 실패');return j})}
function compress(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.max(1,Math.round(img.width*scale));c.height=Math.max(1,Math.round(img.height*scale));c.getContext('2d',{alpha:false}).drawImage(img,0,0,c.width,c.height);c.toBlob(blob=>blob?resolve(blob):reject(new Error('이미지 압축 실패')),'image/webp',.8)};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function blobBase64(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(blob)})}
function safeName(){return `${Date.now()}-${Math.random().toString(36).slice(2,8)}.webp`}
async function uploadBlob(blob,date){const ym=(date||new Date().toISOString().slice(0,7)).replace('.','-').split('-');const folder=`assets/gallery/${ym[0]||'2026'}/${ym[1]||'01'}`;const j=await api('/upload',{method:'POST',body:JSON.stringify({fileName:safeName(),folder,base64:await blobBase64(blob)})});return j.path}
function setPath(o,p,v){const a=p.split('.');let x=o;a.slice(0,-1).forEach(k=>x=x[k]);x[a.at(-1)]=v}
function getPath(o,p){return p.split('.').reduce((x,k)=>x&&x[k],o)}
function preview(img,ref,fallback='../assets/book-room.jpg'){img.src=CMS.image(ref)||fallback}
async function bindBasics(){data=CMS.get();heroEyebrow.value=data.hero.eyebrow;heroTitle.value=data.hero.title;heroSubtitle.value=data.hero.subtitle;greetingTitle.value=data.greeting.title;greetingLead.value=data.greeting.lead;greetingBody1.value=data.greeting.body1;greetingBody2.value=data.greeting.body2;greetingSignature.value=data.greeting.signature;document.querySelectorAll('[data-preview]').forEach(img=>preview(img,getPath(data,img.dataset.preview)))}
function imageField(current,idx,type){return `<label class="wide">사진<input type="file" accept="image/*" data-row-image="${type}" data-index="${idx}"><img class="preview" data-image-ref="${current||''}" src="${CMS.image(current)||'../assets/book-room.jpg'}"></label>`}
function actions(type,i){return `<div class="item-actions"><button data-move="up" data-type="${type}" data-i="${i}">↑</button><button data-move="down" data-type="${type}" data-i="${i}">↓</button><button class="delete" data-delete="${type}" data-i="${i}">삭제</button></div>`}
function renderPhilosophy(){philosophyEditor.innerHTML=data.philosophy.map((x,i)=>`<div class="item-card"><div class="item-head"><strong>보육철학 ${i+1}</strong>${actions('philosophy',i)}</div><div class="item-fields"><label>번호<input data-type="philosophy" data-i="${i}" data-k="num" value="${x.num}"></label><label>제목<input data-type="philosophy" data-i="${i}" data-k="title" value="${x.title}"></label><label class="wide">설명<textarea data-type="philosophy" data-i="${i}" data-k="desc">${x.desc}</textarea></label></div></div>`).join('')}
function renderSpecial(){specialEditor.innerHTML=data.special.map((x,i)=>`<div class="item-card"><div class="item-head"><strong>${x.title||'특별활동'}</strong>${actions('special',i)}</div><div class="item-fields"><label>요일/표시<input data-type="special" data-i="${i}" data-k="day" value="${x.day}"></label><label>활동명<input data-type="special" data-i="${i}" data-k="title" value="${x.title}"></label><label class="wide">설명<textarea data-type="special" data-i="${i}" data-k="desc">${x.desc}</textarea></label>${imageField(x.image,i,'special')}</div></div>`).join('')}
function renderSpaces(){spacesEditor.innerHTML=data.spaces.map((x,i)=>`<div class="item-card"><div class="item-head"><strong>${x.title||'공간'}</strong>${actions('spaces',i)}</div><div class="item-fields"><label>번호<input data-type="spaces" data-i="${i}" data-k="num" value="${x.num}"></label><label>공간명<input data-type="spaces" data-i="${i}" data-k="title" value="${x.title}"></label><label class="wide">공간 설명<textarea data-type="spaces" data-i="${i}" data-k="desc">${x.desc}</textarea></label>${imageField(x.image,i,'spaces')}</div></div>`).join('')}
function renderGallery(){galleryEditor.innerHTML=data.gallery.map((x,i)=>`<div class="item-card"><div class="item-head"><strong>${x.title||'활동사진'}</strong>${actions('gallery',i)}</div><div class="item-fields"><label>분류<select data-type="gallery" data-i="${i}" data-k="category"><option value="food" ${x.category==='food'?'selected':''}>푸드오감</option><option value="forest" ${x.category==='forest'?'selected':''}>숲·자연</option><option value="event" ${x.category==='event'?'selected':''}>행사</option><option value="daily" ${x.category==='daily'?'selected':''}>일상놀이</option></select></label><label>날짜<input data-type="gallery" data-i="${i}" data-k="date" value="${x.date}"></label><label>활동명<input data-type="gallery" data-i="${i}" data-k="title" value="${x.title}"></label><label>짧은 설명<input data-type="gallery" data-i="${i}" data-k="desc" value="${x.desc}"></label>${imageField(x.image,i,'gallery')}</div></div>`).join('')}
async function renderAll(){await bindBasics();renderPhilosophy();renderSpecial();renderSpaces();renderGallery();const c=cfg();workerUrl.value=c.workerUrl||'';adminKey.value=c.adminKey||''}
function collectBasics(){data.hero.eyebrow=heroEyebrow.value;data.hero.title=heroTitle.value;data.hero.subtitle=heroSubtitle.value;data.greeting.title=greetingTitle.value;data.greeting.lead=greetingLead.value;data.greeting.body1=greetingBody1.value;data.greeting.body2=greetingBody2.value;data.greeting.signature=greetingSignature.value}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.type)data[t.dataset.type][+t.dataset.i][t.dataset.k]=t.type==='checkbox'?t.checked:t.value});
document.addEventListener('change',async e=>{const t=e.target;try{if((t.dataset.imageInput||t.dataset.rowImage)&&t.files[0]){toast('사진을 압축하고 GitHub에 올리는 중…');const blob=await compress(t.files[0]);let date=new Date().toISOString().slice(0,7);if(t.dataset.rowImage==='gallery')date=data.gallery[+t.dataset.index].date;const path=await uploadBlob(blob,date);if(t.dataset.imageInput){setPath(data,t.dataset.imageInput,path);preview(document.querySelector(`[data-preview="${t.dataset.imageInput}"]`),path)}else{data[t.dataset.rowImage][+t.dataset.index].image=path;preview(t.parentElement.querySelector('img'),path)}toast('사진 업로드 완료. 전체 저장을 눌러주세요.')}}catch(err){console.error(err);alert(err.message)}});
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.tab){document.querySelectorAll('aside button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));$('#panel-'+b.dataset.tab).classList.add('active')}if(b.dataset.add){const type=b.dataset.add;if(type==='philosophy')data[type].push({num:String(data[type].length+1).padStart(2,'0'),title:'새 보육철학',desc:'설명을 입력하세요.'});if(type==='special')data[type].push({day:'WEEKLY',title:'새 특별활동',desc:'활동 설명을 입력하세요.',image:'assets/activity.jpg'});if(type==='spaces')data[type].push({num:String(data[type].length+1).padStart(2,'0'),title:'새 공간',desc:'공간 설명을 입력하세요.',image:'assets/classroom.jpg'});if(type==='gallery')data[type].unshift({category:'daily',title:'새 활동',desc:'활동 설명을 입력하세요.',date:new Date().toISOString().slice(0,7).replace('-','.'),image:'assets/activity.jpg'});await renderAll()}if(b.dataset.delete&&confirm('이 항목을 삭제할까요?')){const item=data[b.dataset.delete][+b.dataset.i];if(item?.image?.startsWith('assets/gallery/')){try{await api('/delete',{method:'DELETE',body:JSON.stringify({path:item.image})})}catch(err){console.warn(err)}}data[b.dataset.delete].splice(+b.dataset.i,1);await renderAll()}if(b.dataset.move){const a=data[b.dataset.type],i=+b.dataset.i,j=b.dataset.move==='up'?i-1:i+1;if(j>=0&&j<a.length){[a[i],a[j]]=[a[j],a[i]];await renderAll()}}});
async function save(){collectBasics();try{toast('홈페이지에 저장하는 중…');await api('/content',{method:'PUT',body:JSON.stringify({content:data})});CMS.set(data);toast('저장 완료. GitHub Pages 반영에는 약 1~3분 걸립니다.')}catch(e){console.error(e);alert(e.message)}}
saveTop.onclick=save;
saveCloud.onclick=()=>{saveCfg({workerUrl:workerUrl.value.trim(),adminKey:adminKey.value});toast('연결정보를 저장했습니다.')};
testCloud.onclick=async()=>{try{saveCfg({workerUrl:workerUrl.value.trim(),adminKey:adminKey.value});await api('/health');toast('Cloudflare 연결 성공!')}catch(e){alert(e.message)}};
downloadBackup.onclick=()=>{collectBasics();const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='happy-froebel-homepage-backup.json';a.click();URL.revokeObjectURL(a.href)};
restoreFile.onchange=async()=>{try{data=JSON.parse(await restoreFile.files[0].text());CMS.set(data);await renderAll();toast('백업을 불러왔습니다. 전체 저장을 눌러주세요.')}catch(e){alert('올바른 백업파일이 아닙니다.')}};
resetAll.onclick=()=>{if(confirm('로컬 수정 내용을 초기화할까요?'))CMS.reset()};
(async()=>{await CMS.loadRemote();data=CMS.get();await renderAll()})();
